USE [master]
GO

/****** Object:  Database [KxP_hr]    Script Date: 07/29/2024 22:14:35 ******/
CREATE DATABASE [KxP_hr] ON  PRIMARY 
( NAME = N'KxP_hr', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\KxP_hr.mdf' , SIZE = 2304KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'KxP_hr_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\KxP_hr_log.LDF' , SIZE = 576KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [KxP_hr] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [KxP_hr].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [KxP_hr] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [KxP_hr] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [KxP_hr] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [KxP_hr] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [KxP_hr] SET ARITHABORT OFF 
GO

ALTER DATABASE [KxP_hr] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [KxP_hr] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [KxP_hr] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [KxP_hr] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [KxP_hr] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [KxP_hr] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [KxP_hr] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [KxP_hr] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [KxP_hr] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [KxP_hr] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [KxP_hr] SET  ENABLE_BROKER 
GO

ALTER DATABASE [KxP_hr] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [KxP_hr] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [KxP_hr] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [KxP_hr] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [KxP_hr] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [KxP_hr] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [KxP_hr] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [KxP_hr] SET  READ_WRITE 
GO

ALTER DATABASE [KxP_hr] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [KxP_hr] SET  MULTI_USER 
GO

ALTER DATABASE [KxP_hr] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [KxP_hr] SET DB_CHAINING OFF 
GO

